2024-10-08 15:45:57,895 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:45:57
2024-10-08 15:45:58,463 - WARNING - SQLAlchemyError 발생: (psycopg2.errors.UndefinedColumn) 오류:  a.cow_number 칼럼 없음
LINE 4:                                      , a.cow_number
                                               ^
HINT:  아마 "b.cow_number" 칼럼을 참조하는 것 같습니다.

[SQL: 
                                SELECT a.cowactivity_id
                                     , a.cow_id
                                     , a.cow_number
                                     , b.cow_name
                                     , a.counts
                                     , a.counts_perhr
                                     , a.cow_activity
                                     , to_char(a.tstamp, 'YYYYMMDD') AS ymd
                                     , to_char(a.tstamp, 'HH24MMSS') AS hms
                                  FROM tblcowactivities a
                                 INNER JOIN tblcows b
                                        ON a.cow_id = b.cow_id
                                where a.cowactivity_id > %(max_activity_id)s
                                order by a.cow_id, cowactivity_id;
                        ]
[parameters: {'max_activity_id': 0}]
(Background on this error at: https://sqlalche.me/e/20/f405), 1/3 재시도 중...
2024-10-08 15:46:03,767 - INFO - 중지 요청이 접수되었습니다.
2024-10-08 15:48:37,384 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:48:37
2024-10-08 15:48:37,823 - WARNING - SQLAlchemyError 발생: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]'@P9' 근처의 구문이 잘못되었습니다. (102) (SQLExecute); [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]문을 준비할 수 없습니다. (8180)")
[SQL: 
                                INSERT INTO ICT_ACTIVITY_LOG (cowactivity_id, cow_id, cow_number, cow_name, counts, counts_perhr, cow_activity, ymd, hms
                                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?
                                ]
[parameters: [(1135428, 54, 391, '', 966, 21, 87, '20240610', '090653'), (1135519, 54, 391, '', 1070, 26, 108, '20240610', '130613'), (1135565, 54, 391, '', 1253, 90, 409, '20240610', '150628'), (1135665, 54, 391, '', 1319, 30, 136, '20240610', '170639'), (1135784, 54, 391, '', 1487, 30, 111, '20240610', '230650'), (1135902, 54, 391, '', 1594, 19, 86, '20240611', '040650'), (1136097, 54, 391, '', 1718, 19, 90, '20240611', '110615'), (1136218, 54, 391, '', 1954, 43, 148, '20240611', '160634')  ... displaying 10 of 500 total bound parameter sets ...  (1136750, 284, 560, '', 14023, 26, 86, '20240612', '130644'), (1136839, 284, 560, '', 14165, 37, 58, '20240612', '160654')]]
(Background on this error at: https://sqlalche.me/e/20/f405), 1/3 재시도 중...
2024-10-08 15:48:43,489 - INFO - 중지 요청이 접수되었습니다.
2024-10-08 15:48:51,691 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:48:51
2024-10-08 15:48:51,776 - WARNING - SQLAlchemyError 발생: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]'@P9' 근처의 구문이 잘못되었습니다. (102) (SQLExecute); [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]문을 준비할 수 없습니다. (8180)")
[SQL: 
                                INSERT INTO ICT_ACTIVITY_LOG (cowactivity_id, cow_id, cow_number, cow_name, counts, counts_perhr, cow_activity, ymd, hms
                                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?
                                ]
[parameters: [(1135428, 54, 391, '', 966, 21, 87, '20240610', '090653'), (1135519, 54, 391, '', 1070, 26, 108, '20240610', '130613'), (1135565, 54, 391, '', 1253, 90, 409, '20240610', '150628'), (1135665, 54, 391, '', 1319, 30, 136, '20240610', '170639'), (1135784, 54, 391, '', 1487, 30, 111, '20240610', '230650'), (1135902, 54, 391, '', 1594, 19, 86, '20240611', '040650'), (1136097, 54, 391, '', 1718, 19, 90, '20240611', '110615'), (1136218, 54, 391, '', 1954, 43, 148, '20240611', '160634')  ... displaying 10 of 500 total bound parameter sets ...  (1136750, 284, 560, '', 14023, 26, 86, '20240612', '130644'), (1136839, 284, 560, '', 14165, 37, 58, '20240612', '160654')]]
(Background on this error at: https://sqlalche.me/e/20/f405), 1/3 재시도 중...
2024-10-08 15:49:01,701 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:49:01
2024-10-08 15:49:01,794 - WARNING - SQLAlchemyError 발생: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]'@P9' 근처의 구문이 잘못되었습니다. (102) (SQLExecute); [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]문을 준비할 수 없습니다. (8180)")
[SQL: 
                                INSERT INTO ICT_ACTIVITY_LOG (cowactivity_id, cow_id, cow_number, cow_name, counts, counts_perhr, cow_activity, ymd, hms
                                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?
                                ]
[parameters: [(1135428, 54, 391, '', 966, 21, 87, '20240610', '090653'), (1135519, 54, 391, '', 1070, 26, 108, '20240610', '130613'), (1135565, 54, 391, '', 1253, 90, 409, '20240610', '150628'), (1135665, 54, 391, '', 1319, 30, 136, '20240610', '170639'), (1135784, 54, 391, '', 1487, 30, 111, '20240610', '230650'), (1135902, 54, 391, '', 1594, 19, 86, '20240611', '040650'), (1136097, 54, 391, '', 1718, 19, 90, '20240611', '110615'), (1136218, 54, 391, '', 1954, 43, 148, '20240611', '160634')  ... displaying 10 of 500 total bound parameter sets ...  (1136750, 284, 560, '', 14023, 26, 86, '20240612', '130644'), (1136839, 284, 560, '', 14165, 37, 58, '20240612', '160654')]]
(Background on this error at: https://sqlalche.me/e/20/f405), 2/3 재시도 중...
2024-10-08 15:49:05,465 - INFO - 중지 요청이 접수되었습니다.
2024-10-08 15:51:59,323 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:51:59
2024-10-08 15:52:00,294 - INFO - 데이터 수집 종료 시간: 2024.10.08 15:52:00

2024-10-08 15:52:09,348 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:52:09
2024-10-08 15:52:19,337 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:52:19
2024-10-08 15:52:29,294 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:52:29
2024-10-08 15:52:29,863 - INFO - 데이터 수집 종료 시간: 2024.10.08 15:52:29

2024-10-08 15:52:39,349 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:52:39
2024-10-08 15:52:39,916 - INFO - 데이터 수집 종료 시간: 2024.10.08 15:52:39

2024-10-08 15:52:49,362 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:52:49
2024-10-08 15:52:59,330 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:52:59
2024-10-08 15:53:09,330 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:53:09
2024-10-08 15:53:19,319 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:53:19
2024-10-08 15:53:29,301 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:53:29
2024-10-08 15:53:29,584 - INFO - 데이터 수집 종료 시간: 2024.10.08 15:53:29

2024-10-08 15:53:39,358 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:53:39
2024-10-08 15:53:49,335 - INFO - 데이터 수집 시작 시간 : 2024.10.08 15:53:49
2024-10-08 15:53:59,320 - INFO - 중지 요청이 접수되었습니다.
2024-10-08 17:11:07,159 - INFO - 중지 요청이 접수되었습니다.
2024-10-08 17:12:10,648 - INFO - 중지 요청이 접수되었습니다.
2024-10-08 17:13:10,670 - INFO - 중지 요청이 접수되었습니다.
2024-10-08 17:13:55,944 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:13:55
2024-10-08 17:13:56,325 - WARNING - OperationalError 발생: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: fe_sendauth: no password supplied

(Background on this error at: https://sqlalche.me/e/20/e3q8), 1/3 재시도 중...
2024-10-08 17:14:16,537 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:14:16
2024-10-08 17:14:17,514 - INFO - 데이터 수집 종료 시간: 2024.10.08 17:14:17

2024-10-08 17:14:26,555 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:14:26
2024-10-08 17:14:36,530 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:14:36
2024-10-08 17:14:46,504 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:14:46
2024-10-08 17:14:56,478 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:14:56
2024-10-08 17:15:06,442 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:15:06
2024-10-08 17:15:06,812 - INFO - 데이터 수집 종료 시간: 2024.10.08 17:15:06

2024-10-08 17:15:09,904 - INFO - 중지 요청이 접수되었습니다.
2024-10-08 17:15:32,587 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:15:32
2024-10-08 17:15:42,595 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:15:42
2024-10-08 17:15:42,871 - INFO - 데이터 수집 종료 시간: 2024.10.08 17:15:42

2024-10-08 17:15:52,619 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:15:52
2024-10-08 17:16:02,588 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:16:02
2024-10-08 17:16:12,543 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:16:12
2024-10-08 17:16:22,511 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:16:22
2024-10-08 17:16:32,472 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:16:32
2024-10-08 17:16:42,433 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:16:42
2024-10-08 17:16:52,395 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:16:52
2024-10-08 17:17:02,349 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:17:02
2024-10-08 17:17:12,316 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:17:12
2024-10-08 17:17:22,285 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:17:22
2024-10-08 17:17:32,251 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:17:32
2024-10-08 17:17:32,563 - INFO - 중지 요청이 접수되었습니다.
2024-10-08 17:34:05,416 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:34:05
2024-10-08 17:34:05,694 - WARNING - OperationalError 발생: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: fe_sendauth: no password supplied

(Background on this error at: https://sqlalche.me/e/20/e3q8), 1/3 재시도 중...
2024-10-08 17:34:09,787 - INFO - 중지 요청이 접수되었습니다.
2024-10-08 17:34:23,711 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:34:23
2024-10-08 17:34:33,697 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:34:33
2024-10-08 17:34:43,655 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:34:43
2024-10-08 17:34:43,971 - INFO - 데이터 수집 종료 시간: 2024.10.08 17:34:43

2024-10-08 17:34:46,127 - INFO - 중지 요청이 접수되었습니다.
2024-10-08 17:35:32,012 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:35:32
2024-10-08 17:35:40,243 - INFO - 중지 요청이 접수되었습니다.
2024-10-08 17:35:58,392 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:35:58
2024-10-08 17:36:06,557 - INFO - 중지 요청이 접수되었습니다.
2024-10-08 17:36:17,118 - INFO - 데이터 수집 시작 시간 : 2024.10.08 17:36:17
2024-10-08 17:36:23,164 - INFO - 중지 요청이 접수되었습니다.
